name: flutterw_sidekick_plugin
description: Sidekick plugin that installs flutter_wrapper in the repository and links it to the flutter and dart commands
version: 1.2.0
repository: https://github.com/passsy/flutterw_sidekick_plugin
issue_tracker: https://github.com/passsy/flutterw_sidekick_plugin/issues
topics:
  - sidekick
  - sidekick-plugin
  - flutter-wrapper
  - flutter-version-management
  - fvm

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dcli: ^4.0.4
  sidekick_core: ^3.0.0-preview.1

dev_dependencies:
  analyzer: '>=4.0.0 <7.0.0'
  dart_style: ^2.2.0
  indent: ^2.0.0
  lint: '>=1.5.0 <=3.0.0'
  pub_semver: ^2.1.2
  sidekick_plugin_installer: ^1.2.1
  test: ^1.21.0
  yaml: ^3.1.1
