name: flutterw_sidekick_plugin
description: Generated sidekick plugin (template shared-command)
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  dart_style: ^2.2.0
  dcli: # version provided by sidekick_core
  indent: ^2.0.0
  sidekick_core: '>=0.8.0 <1.0.0'

dev_dependencies:
  lint: ^1.5.0
  sidekick_plugin_installer: ^0.1.3
  test: ^1.21.0
