name: flutterw_sidekick_plugin
description: Sidekick plugin that installs flutter_wrapper in the repository and links it to the flutter and dart commands
version: 0.2.1
repository: https://github.com/passsy/flutterw_sidekick_plugin
issue_tracker: https://github.com/passsy/flutterw_sidekick_plugin/issues
topics:
  - sidekick
  - sidekick-plugin
  - flutter_wrapper
  - flutter_version_management

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dcli: ^2.2.0
  sidekick_core: ^2.0.0-preview.1

dev_dependencies:
  analyzer: '>=4.0.0 <6.0.0'
  dart_style: ^2.2.0
  indent: ^2.0.0
  lint: '>=1.5.0 <=3.0.0'
  pub_semver: ^2.1.2
  sidekick_plugin_installer: ^1.0.0
  test: ^1.21.0
  yaml: ^3.1.1
